#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.237
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestorTransmisionService
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="GestorDocumental")]
	public partial class basdatDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void InsertParametros(Parametros instance);
    partial void UpdateParametros(Parametros instance);
    partial void DeleteParametros(Parametros instance);
    partial void InsertTransmision(Transmision instance);
    partial void UpdateTransmision(Transmision instance);
    partial void DeleteTransmision(Transmision instance);
    partial void InsertConsecutivos(Consecutivos instance);
    partial void UpdateConsecutivos(Consecutivos instance);
    partial void DeleteConsecutivos(Consecutivos instance);
    #endregion
		
		public basdatDataContext() : 
				base(global::GestorTransmisionService.Properties.Settings.Default.GestorDocumentalConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public basdatDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public basdatDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public basdatDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public basdatDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Parametros> Parametros
		{
			get
			{
				return this.GetTable<Parametros>();
			}
		}
		
		public System.Data.Linq.Table<Transmision> Transmision
		{
			get
			{
				return this.GetTable<Transmision>();
			}
		}
		
		public System.Data.Linq.Table<Consecutivos> Consecutivos
		{
			get
			{
				return this.GetTable<Consecutivos>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Parametros")]
	public partial class Parametros : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private short _id;
		
		private string _codigo;
		
		private string _valor;
		
		private string _descripcion;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(short value);
    partial void OnidChanged();
    partial void OncodigoChanging(string value);
    partial void OncodigoChanged();
    partial void OnvalorChanging(string value);
    partial void OnvalorChanged();
    partial void OndescripcionChanging(string value);
    partial void OndescripcionChanged();
    #endregion
		
		public Parametros()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="SmallInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public short id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codigo", DbType="VarChar(50)")]
		public string codigo
		{
			get
			{
				return this._codigo;
			}
			set
			{
				if ((this._codigo != value))
				{
					this.OncodigoChanging(value);
					this.SendPropertyChanging();
					this._codigo = value;
					this.SendPropertyChanged("codigo");
					this.OncodigoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_valor", DbType="VarChar(200)")]
		public string valor
		{
			get
			{
				return this._valor;
			}
			set
			{
				if ((this._valor != value))
				{
					this.OnvalorChanging(value);
					this.SendPropertyChanging();
					this._valor = value;
					this.SendPropertyChanged("valor");
					this.OnvalorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descripcion", DbType="VarChar(200)")]
		public string descripcion
		{
			get
			{
				return this._descripcion;
			}
			set
			{
				if ((this._descripcion != value))
				{
					this.OndescripcionChanging(value);
					this.SendPropertyChanging();
					this._descripcion = value;
					this.SendPropertyChanged("descripcion");
					this.OndescripcionChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Transmision")]
	public partial class Transmision : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _storeProcedure;
		
		private string _delimitador;
		
		private string _nomArchivo;
		
		private string _extArchivo;
		
		private string _rutaArchivo;
		
		private string _hora;
		
		private string _tipo;
		
		private string _descripcion;
		
		private System.Nullable<bool> _procesado;
		
		private System.Nullable<System.DateTime> _fecProceso;
		
		private System.Nullable<bool> _activo;
		
		private System.Nullable<int> _orden;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnstoreProcedureChanging(string value);
    partial void OnstoreProcedureChanged();
    partial void OndelimitadorChanging(string value);
    partial void OndelimitadorChanged();
    partial void OnnomArchivoChanging(string value);
    partial void OnnomArchivoChanged();
    partial void OnextArchivoChanging(string value);
    partial void OnextArchivoChanged();
    partial void OnrutaArchivoChanging(string value);
    partial void OnrutaArchivoChanged();
    partial void OnhoraChanging(string value);
    partial void OnhoraChanged();
    partial void OntipoChanging(string value);
    partial void OntipoChanged();
    partial void OndescripcionChanging(string value);
    partial void OndescripcionChanged();
    partial void OnprocesadoChanging(System.Nullable<bool> value);
    partial void OnprocesadoChanged();
    partial void OnfecProcesoChanging(System.Nullable<System.DateTime> value);
    partial void OnfecProcesoChanged();
    partial void OnactivoChanging(System.Nullable<bool> value);
    partial void OnactivoChanged();
    partial void OnordenChanging(System.Nullable<int> value);
    partial void OnordenChanged();
    #endregion
		
		public Transmision()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_storeProcedure", DbType="VarChar(100)")]
		public string storeProcedure
		{
			get
			{
				return this._storeProcedure;
			}
			set
			{
				if ((this._storeProcedure != value))
				{
					this.OnstoreProcedureChanging(value);
					this.SendPropertyChanging();
					this._storeProcedure = value;
					this.SendPropertyChanged("storeProcedure");
					this.OnstoreProcedureChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_delimitador", DbType="VarChar(2)")]
		public string delimitador
		{
			get
			{
				return this._delimitador;
			}
			set
			{
				if ((this._delimitador != value))
				{
					this.OndelimitadorChanging(value);
					this.SendPropertyChanging();
					this._delimitador = value;
					this.SendPropertyChanged("delimitador");
					this.OndelimitadorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nomArchivo", DbType="VarChar(50)")]
		public string nomArchivo
		{
			get
			{
				return this._nomArchivo;
			}
			set
			{
				if ((this._nomArchivo != value))
				{
					this.OnnomArchivoChanging(value);
					this.SendPropertyChanging();
					this._nomArchivo = value;
					this.SendPropertyChanged("nomArchivo");
					this.OnnomArchivoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_extArchivo", DbType="VarChar(50)")]
		public string extArchivo
		{
			get
			{
				return this._extArchivo;
			}
			set
			{
				if ((this._extArchivo != value))
				{
					this.OnextArchivoChanging(value);
					this.SendPropertyChanging();
					this._extArchivo = value;
					this.SendPropertyChanged("extArchivo");
					this.OnextArchivoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rutaArchivo", DbType="VarChar(100)")]
		public string rutaArchivo
		{
			get
			{
				return this._rutaArchivo;
			}
			set
			{
				if ((this._rutaArchivo != value))
				{
					this.OnrutaArchivoChanging(value);
					this.SendPropertyChanging();
					this._rutaArchivo = value;
					this.SendPropertyChanged("rutaArchivo");
					this.OnrutaArchivoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hora", DbType="VarChar(50)")]
		public string hora
		{
			get
			{
				return this._hora;
			}
			set
			{
				if ((this._hora != value))
				{
					this.OnhoraChanging(value);
					this.SendPropertyChanging();
					this._hora = value;
					this.SendPropertyChanged("hora");
					this.OnhoraChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tipo", DbType="VarChar(50)")]
		public string tipo
		{
			get
			{
				return this._tipo;
			}
			set
			{
				if ((this._tipo != value))
				{
					this.OntipoChanging(value);
					this.SendPropertyChanging();
					this._tipo = value;
					this.SendPropertyChanged("tipo");
					this.OntipoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descripcion", DbType="VarChar(500)")]
		public string descripcion
		{
			get
			{
				return this._descripcion;
			}
			set
			{
				if ((this._descripcion != value))
				{
					this.OndescripcionChanging(value);
					this.SendPropertyChanging();
					this._descripcion = value;
					this.SendPropertyChanged("descripcion");
					this.OndescripcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_procesado", DbType="Bit")]
		public System.Nullable<bool> procesado
		{
			get
			{
				return this._procesado;
			}
			set
			{
				if ((this._procesado != value))
				{
					this.OnprocesadoChanging(value);
					this.SendPropertyChanging();
					this._procesado = value;
					this.SendPropertyChanged("procesado");
					this.OnprocesadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecProceso", DbType="DateTime")]
		public System.Nullable<System.DateTime> fecProceso
		{
			get
			{
				return this._fecProceso;
			}
			set
			{
				if ((this._fecProceso != value))
				{
					this.OnfecProcesoChanging(value);
					this.SendPropertyChanging();
					this._fecProceso = value;
					this.SendPropertyChanged("fecProceso");
					this.OnfecProcesoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_activo", DbType="Bit")]
		public System.Nullable<bool> activo
		{
			get
			{
				return this._activo;
			}
			set
			{
				if ((this._activo != value))
				{
					this.OnactivoChanging(value);
					this.SendPropertyChanging();
					this._activo = value;
					this.SendPropertyChanged("activo");
					this.OnactivoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_orden", DbType="Int")]
		public System.Nullable<int> orden
		{
			get
			{
				return this._orden;
			}
			set
			{
				if ((this._orden != value))
				{
					this.OnordenChanging(value);
					this.SendPropertyChanging();
					this._orden = value;
					this.SendPropertyChanged("orden");
					this.OnordenChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Consecutivos")]
	public partial class Consecutivos : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ConId;
		
		private string _ConDescripcion;
		
		private string _ConCodigo;
		
		private System.Nullable<int> _ConValor;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnConIdChanging(int value);
    partial void OnConIdChanged();
    partial void OnConDescripcionChanging(string value);
    partial void OnConDescripcionChanged();
    partial void OnConCodigoChanging(string value);
    partial void OnConCodigoChanged();
    partial void OnConValorChanging(System.Nullable<int> value);
    partial void OnConValorChanged();
    #endregion
		
		public Consecutivos()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ConId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ConId
		{
			get
			{
				return this._ConId;
			}
			set
			{
				if ((this._ConId != value))
				{
					this.OnConIdChanging(value);
					this.SendPropertyChanging();
					this._ConId = value;
					this.SendPropertyChanged("ConId");
					this.OnConIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ConDescripcion", DbType="VarChar(200)")]
		public string ConDescripcion
		{
			get
			{
				return this._ConDescripcion;
			}
			set
			{
				if ((this._ConDescripcion != value))
				{
					this.OnConDescripcionChanging(value);
					this.SendPropertyChanging();
					this._ConDescripcion = value;
					this.SendPropertyChanged("ConDescripcion");
					this.OnConDescripcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ConCodigo", DbType="VarChar(30)")]
		public string ConCodigo
		{
			get
			{
				return this._ConCodigo;
			}
			set
			{
				if ((this._ConCodigo != value))
				{
					this.OnConCodigoChanging(value);
					this.SendPropertyChanging();
					this._ConCodigo = value;
					this.SendPropertyChanged("ConCodigo");
					this.OnConCodigoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ConValor", DbType="Int")]
		public System.Nullable<int> ConValor
		{
			get
			{
				return this._ConValor;
			}
			set
			{
				if ((this._ConValor != value))
				{
					this.OnConValorChanging(value);
					this.SendPropertyChanging();
					this._ConValor = value;
					this.SendPropertyChanged("ConValor");
					this.OnConValorChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
