#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.237
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceImpresionGNF
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="GestorDocumentalGNF_Pruebas")]
	public partial class BaseDatosDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void InsertParametros(Parametros instance);
    partial void UpdateParametros(Parametros instance);
    partial void DeleteParametros(Parametros instance);
    partial void InsertCodigosBarras(CodigosBarras instance);
    partial void UpdateCodigosBarras(CodigosBarras instance);
    partial void DeleteCodigosBarras(CodigosBarras instance);
    #endregion
		
		public BaseDatosDataContext() : 
				base(global::ServiceImpresionGNF.Properties.Settings.Default.GestorDocumentalGNFConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public BaseDatosDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BaseDatosDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BaseDatosDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BaseDatosDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Parametros> Parametros
		{
			get
			{
				return this.GetTable<Parametros>();
			}
		}
		
		public System.Data.Linq.Table<CodigosBarras> CodigosBarras
		{
			get
			{
				return this.GetTable<CodigosBarras>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Parametros")]
	public partial class Parametros : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private short _id;
		
		private string _codigo;
		
		private string _valor;
		
		private string _descripcion;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(short value);
    partial void OnidChanged();
    partial void OncodigoChanging(string value);
    partial void OncodigoChanged();
    partial void OnvalorChanging(string value);
    partial void OnvalorChanged();
    partial void OndescripcionChanging(string value);
    partial void OndescripcionChanged();
    #endregion
		
		public Parametros()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="SmallInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public short id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codigo", DbType="VarChar(50)")]
		public string codigo
		{
			get
			{
				return this._codigo;
			}
			set
			{
				if ((this._codigo != value))
				{
					this.OncodigoChanging(value);
					this.SendPropertyChanging();
					this._codigo = value;
					this.SendPropertyChanged("codigo");
					this.OncodigoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_valor", DbType="VarChar(200)")]
		public string valor
		{
			get
			{
				return this._valor;
			}
			set
			{
				if ((this._valor != value))
				{
					this.OnvalorChanging(value);
					this.SendPropertyChanging();
					this._valor = value;
					this.SendPropertyChanged("valor");
					this.OnvalorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descripcion", DbType="VarChar(200)")]
		public string descripcion
		{
			get
			{
				return this._descripcion;
			}
			set
			{
				if ((this._descripcion != value))
				{
					this.OndescripcionChanging(value);
					this.SendPropertyChanging();
					this._descripcion = value;
					this.SendPropertyChanged("descripcion");
					this.OndescripcionChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CodigosBarras")]
	public partial class CodigosBarras : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _IdCodBarras;
		
		private System.Nullable<long> _IdRadicacion;
		
		private string _CodigoZPL;
		
		private string _impresora;
		
		private System.Nullable<int> _estado;
		
		private System.Nullable<System.DateTime> _FechaImpreso;
		
		private System.Nullable<decimal> _usuario;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdCodBarrasChanging(long value);
    partial void OnIdCodBarrasChanged();
    partial void OnIdRadicacionChanging(System.Nullable<long> value);
    partial void OnIdRadicacionChanged();
    partial void OnCodigoZPLChanging(string value);
    partial void OnCodigoZPLChanged();
    partial void OnimpresoraChanging(string value);
    partial void OnimpresoraChanged();
    partial void OnestadoChanging(System.Nullable<int> value);
    partial void OnestadoChanged();
    partial void OnFechaImpresoChanging(System.Nullable<System.DateTime> value);
    partial void OnFechaImpresoChanged();
    partial void OnusuarioChanging(System.Nullable<decimal> value);
    partial void OnusuarioChanged();
    #endregion
		
		public CodigosBarras()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdCodBarras", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long IdCodBarras
		{
			get
			{
				return this._IdCodBarras;
			}
			set
			{
				if ((this._IdCodBarras != value))
				{
					this.OnIdCodBarrasChanging(value);
					this.SendPropertyChanging();
					this._IdCodBarras = value;
					this.SendPropertyChanged("IdCodBarras");
					this.OnIdCodBarrasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdRadicacion", DbType="BigInt")]
		public System.Nullable<long> IdRadicacion
		{
			get
			{
				return this._IdRadicacion;
			}
			set
			{
				if ((this._IdRadicacion != value))
				{
					this.OnIdRadicacionChanging(value);
					this.SendPropertyChanging();
					this._IdRadicacion = value;
					this.SendPropertyChanged("IdRadicacion");
					this.OnIdRadicacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodigoZPL", DbType="NVarChar(MAX)")]
		public string CodigoZPL
		{
			get
			{
				return this._CodigoZPL;
			}
			set
			{
				if ((this._CodigoZPL != value))
				{
					this.OnCodigoZPLChanging(value);
					this.SendPropertyChanging();
					this._CodigoZPL = value;
					this.SendPropertyChanged("CodigoZPL");
					this.OnCodigoZPLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_impresora", DbType="NVarChar(100)")]
		public string impresora
		{
			get
			{
				return this._impresora;
			}
			set
			{
				if ((this._impresora != value))
				{
					this.OnimpresoraChanging(value);
					this.SendPropertyChanging();
					this._impresora = value;
					this.SendPropertyChanged("impresora");
					this.OnimpresoraChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_estado", DbType="Int")]
		public System.Nullable<int> estado
		{
			get
			{
				return this._estado;
			}
			set
			{
				if ((this._estado != value))
				{
					this.OnestadoChanging(value);
					this.SendPropertyChanging();
					this._estado = value;
					this.SendPropertyChanged("estado");
					this.OnestadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaImpreso", DbType="DateTime")]
		public System.Nullable<System.DateTime> FechaImpreso
		{
			get
			{
				return this._FechaImpreso;
			}
			set
			{
				if ((this._FechaImpreso != value))
				{
					this.OnFechaImpresoChanging(value);
					this.SendPropertyChanging();
					this._FechaImpreso = value;
					this.SendPropertyChanged("FechaImpreso");
					this.OnFechaImpresoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usuario", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> usuario
		{
			get
			{
				return this._usuario;
			}
			set
			{
				if ((this._usuario != value))
				{
					this.OnusuarioChanging(value);
					this.SendPropertyChanging();
					this._usuario = value;
					this.SendPropertyChanged("usuario");
					this.OnusuarioChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
